/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw01.gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class HelloOtusTest {
    @Test void appHasAGreeting() {
        HelloOtus classUnderTest = new HelloOtus();
        assertNotNull(classUnderTest.getGreetingGuava(), "app should have a Array to String Guava conversion");
    }
}
