/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw01.gradle;

import com.google.common.base.Joiner;
import java.util.Arrays;

public class HelloOtus {
    public String getGreetingGuava() {
        System.out.println("Call Guava String Joiner for Array with NULL values (skipped)");
        return Joiner.on(",")
                .skipNulls()
                .join(Arrays.asList(1,2,3,4,5,null,6));
    }

    public static void main(String[] args) {
        System.out.println(new HelloOtus().getGreetingGuava());
    }
}
